server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/company_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 78000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

dubbo:
  application:
    name: company-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
    timeout: 10000
  scan:
    base-packages: com.company.provider.service

logging:
  level:
    com.company.provider: debug
